import os
import sys
import psycopg2
from dotenv import load_dotenv

# Load environment variables from the client's .env file
env_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../client/.env"))
if not os.path.exists(env_path):
    print(f"Error: .env file not found at {env_path}")
    sys.exit(1)

load_dotenv(dotenv_path=env_path)

supabase_url = os.getenv("VITE_SUPABASE_URL")
db_password = os.getenv("supabase_pwd")

if not supabase_url or not db_password:
    print("Error: Missing VITE_SUPABASE_URL or supabase_pwd in .env file.")
    sys.exit(1)

# Extract host from VITE_SUPABASE_URL
project_id = supabase_url.replace("https://", "").replace(".supabase.co", "")
db_host = f"db.{project_id}.supabase.co"
db_port = "5432"
db_name = "postgres"
db_user = "postgres"

print(f"Connecting to database host: {db_host} to create 'users' table...")

sql_queries = [
    """
    CREATE TABLE IF NOT EXISTS public.users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email TEXT UNIQUE NOT NULL,
        password TEXT NOT NULL,
        role TEXT NOT NULL DEFAULT 'customer',
        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
    );
    """,
    """
    ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
    """,
    """
    DROP POLICY IF EXISTS "Allow public write/read access on users" ON public.users;
    """,
    """
    CREATE POLICY "Allow public write/read access on users" 
    ON public.users FOR ALL 
    USING (true) 
    WITH CHECK (true);
    """
]

try:
    # Connect to the PostgreSQL database
    conn = psycopg2.connect(
        host=db_host,
        port=db_port,
        database=db_name,
        user=db_user,
        password=db_password
    )
    conn.autocommit = True
    cursor = conn.cursor()

    print("Executing users table creation queries...")
    for query in sql_queries:
        cursor.execute(query)
    
    print("Table public.users created/verified successfully!")
    
    cursor.close()
    conn.close()
except Exception as e:
    print(f"Database connection or query failed: {e}")
    sys.exit(1)
