import os
import sys
import psycopg2
from dotenv import load_dotenv

# Load environment variables from the client's .env file
env_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../client/.env"))
if not os.path.exists(env_path):
    print(f"Error: .env file not found at {env_path}")
    sys.exit(1)

load_dotenv(dotenv_path=env_path)

supabase_url = os.getenv("VITE_SUPABASE_URL")
db_password = os.getenv("supabase_pwd")

if not supabase_url or not db_password:
    print("Error: Missing VITE_SUPABASE_URL or supabase_pwd in .env file.")
    sys.exit(1)

# Extract host from VITE_SUPABASE_URL
# Example: https://jdjjmwbbahewaampqfqd.supabase.co -> db.jdjjmwbbahewaampqfqd.supabase.co
project_id = supabase_url.replace("https://", "").replace(".supabase.co", "")
db_host = f"db.{project_id}.supabase.co"
db_port = "5432"
db_name = "postgres"
db_user = "postgres"

print(f"Connecting to database host: {db_host}...")

sql_queries = [
    """
    CREATE TABLE IF NOT EXISTS public.cart_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_email TEXT NOT NULL,
        product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
        quantity INTEGER NOT NULL DEFAULT 1,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
        UNIQUE(user_email, product_id)
    );
    """,
    """
    ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
    """,
    """
    DROP POLICY IF EXISTS "Allow public write/read access on cart_items" ON public.cart_items;
    """,
    """
    CREATE POLICY "Allow public write/read access on cart_items" 
    ON public.cart_items FOR ALL 
    USING (true) 
    WITH CHECK (true);
    """
]

try:
    # Connect to the PostgreSQL database
    conn = psycopg2.connect(
        host=db_host,
        port=db_port,
        database=db_name,
        user=db_user,
        password=db_password
    )
    conn.autocommit = True
    cursor = conn.cursor()

    print("Executing table creation queries...")
    for query in sql_queries:
        cursor.execute(query)
    
    print("Table public.cart_items created/verified successfully!")
    
    cursor.close()
    conn.close()
except Exception as e:
    print(f"Database connection or query failed: {e}")
    sys.exit(1)
