-- ValueBay Database Schema
-- Run this script in the Supabase SQL Editor to create the necessary tables.

-- 1. Create the Categories Table
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create the Products Table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT PRIMARY KEY, -- Using manual IDs matching client data
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    original_price NUMERIC,
    rating NUMERIC DEFAULT 4.5,
    review_count INTEGER DEFAULT 0,
    category TEXT REFERENCES public.categories(name) ON UPDATE CASCADE ON DELETE SET NULL,
    image TEXT,
    in_stock BOOLEAN DEFAULT TRUE,
    sales_tag TEXT,
    condition_text TEXT,
    description TEXT,
    features TEXT[] DEFAULT '{}',
    specifications JSONB DEFAULT '{}',
    reviews JSONB DEFAULT '[]',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 4. Create Public Read Access Policies (Allow anyone to view products and categories)
DROP POLICY IF EXISTS "Allow public read access on categories" ON public.categories;
CREATE POLICY "Allow public read access on categories" 
ON public.categories FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Allow public read access on products" ON public.products;
CREATE POLICY "Allow public read access on products" 
ON public.products FOR SELECT 
USING (true);

-- 5. Create Write Policies (Allow public/seeder script to insert/update/delete)
DROP POLICY IF EXISTS "Allow write access on categories" ON public.categories;
DROP POLICY IF EXISTS "Allow service_role write access on categories" ON public.categories;
CREATE POLICY "Allow write access on categories" 
ON public.categories FOR ALL 
USING (true) 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow write access on products" ON public.products;
DROP POLICY IF EXISTS "Allow service_role write access on products" ON public.products;
CREATE POLICY "Allow write access on products" 
ON public.products FOR ALL 
USING (true) 
WITH CHECK (true);

-- 6. Create the Cart Items Table
CREATE TABLE IF NOT EXISTS public.cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, product_id)
);

-- Enable RLS
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;

-- Allow public write/read access on cart_items
DROP POLICY IF EXISTS "Allow public write/read access on cart_items" ON public.cart_items;
CREATE POLICY "Allow public write/read access on cart_items" 
ON public.cart_items FOR ALL 
USING (true) 
WITH CHECK (true);

-- 7. Create the Users Table
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'customer',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Allow public write/read access on users
DROP POLICY IF EXISTS "Allow public write/read access on users" ON public.users;
CREATE POLICY "Allow public write/read access on users" 
ON public.users FOR ALL 
USING (true) 
WITH CHECK (true);


